name: e_commerce_app
description: "E-Commerce Mobile App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"


flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/all/
    - images/beauty/
    - images/jewelry/
    - images/men fashion/
    - images/shoes/
    - images/women fashion/